INSERT INTO members (first_name, last_name, major, status) VALUES ('Abril', 'Zuniga', 'Bioinformatics & Medical Informatics', 'Auxillary');
INSERT INTO members (first_name, last_name, major, status) VALUES ('Allison', 'Jue', 'Bioinformatics & Medical Informatics', 'Graduate');
INSERT INTO members (first_name, last_name, major, status) VALUES ('Ariana', 'Beloiu', 'Bioinformatics & Medical Informatics', 'Graduate');
INSERT INTO members (first_name, last_name, major, status) VALUES ('Ben', 'Caulfield', 'Bioinformatics & Medical Informatics', 'Auxillary');
INSERT INTO members (first_name, last_name, major, status) VALUES ('Blake', 'Gabel', 'Bioinformatics & Medical Informatics', '');
INSERT INTO members (first_name, last_name, major, status) VALUES ('Branden', 'La Madrid', 'Bioinformatics & Medical Informatics', 'Graduate');
INSERT INTO members (first_name, last_name, major, status) VALUES ('Brandon', 'Wong', 'Bioinformatics & Medical Informatics', 'Graduate');
INSERT INTO members (first_name, last_name, major, status) VALUES ('Carolina', 'Parra', 'Bioinformatics & Medical Informatics', '');
INSERT INTO members (first_name, last_name, major, status) VALUES ('Daniela', 'Samperio', 'Biology', 'General');
INSERT INTO members (first_name, last_name, major, status) VALUES ('Darshini', 'Parekh', 'Bioinformatics & Medical Informatics', '');
INSERT INTO members (first_name, last_name, major, status) VALUES ('Francis', 'Le', 'Bioinformatics & Medical Informatics', 'Graduate');
INSERT INTO members (first_name, last_name, major, status) VALUES ('Jasmine', 'Yabut', 'Bioinformatics & Medical Informatics', 'General');
INSERT INTO members (first_name, last_name, major, status) VALUES ('Kaya', 'Hoffman', 'Bioinformatics & Medical Informatics', 'Graduate');
INSERT INTO members (first_name, last_name, major, status) VALUES ('Kayla', 'Poirier', 'Bioinformatics & Medical Informatics', 'VP Engagement');
INSERT INTO members (first_name, last_name, major, status) VALUES ('Lyndon', 'Torio', 'Bioinformatics & Medical Informatics', 'Auxillary');
INSERT INTO members (first_name, last_name, major, status) VALUES ('Margarita', 'Martinez', 'Bioinformatics & Medical Informatics', '');
INSERT INTO members (first_name, last_name, major, status) VALUES ('Maria', 'Troisi', 'Bioinformatics & Medical Informatics', 'Auxillary');
INSERT INTO members (first_name, last_name, major, status) VALUES ('Mary', 'Ford', 'Bioinformatics & Medical Informatics', '');
INSERT INTO members (first_name, last_name, major, status) VALUES ('Meilyn', 'Lu', 'Bioinformatics & Medical Informatics', 'Graduate');
INSERT INTO members (first_name, last_name, major, status) VALUES ('Melissa', 'Samperio', 'Bioinformatics & Medical Informatics', 'Treasurer');
INSERT INTO members (first_name, last_name, major, status) VALUES ('Micah', 'Becchio', 'Bioinformatics & Medical Informatics', '');
INSERT INTO members (first_name, last_name, major, status) VALUES ('Mrunal', 'Natu', 'Bioinformatics & Medical Informatics', 'Secretary');
INSERT INTO members (first_name, last_name, major, status) VALUES ('Nachiket', 'Thosar', 'Bioinformatics & Medical Informatics', '');
INSERT INTO members (first_name, last_name, major, status) VALUES ('Natalia', 'Contreras', 'Bioinformatics & Medical Informatics', 'President');
INSERT INTO members (first_name, last_name, major, status) VALUES ('Nhi', 'Nguyen', 'Bioinformatics & Medical Informatics', 'Graduate');
INSERT INTO members (first_name, last_name, major, status) VALUES ('Nivedita', 'Puliadi Subramanian', 'Bioinformatics & Medical Informatics', 'Auxillary');
INSERT INTO members (first_name, last_name, major, status) VALUES ('Priyanshi', 'Shah', 'Bioinformatics & Medical Informatics', 'Auxillary');
INSERT INTO members (first_name, last_name, major, status) VALUES ('Reina', 'Hastings', 'Bioinformatics & Medical Informatics', 'Graduate');
INSERT INTO members (first_name, last_name, major, status) VALUES ('Riley', 'Jones', 'Bioinformatics & Medical Informatics', 'Auxillary');
INSERT INTO members (first_name, last_name, major, status) VALUES ('Rosstin', 'Rouzbehani', 'Bioinformatics & Medical Informatics', 'Graduate');
INSERT INTO members (first_name, last_name, major, status) VALUES ('Ryan', 'Blevitt', 'Bioinformatics & Medical Informatics', 'Graduate');
INSERT INTO members (first_name, last_name, major, status) VALUES ('Samantha', 'Gallegos Perez', 'Bioinformatics & Medical Informatics', 'Graduate');
INSERT INTO members (first_name, last_name, major, status) VALUES ('Sean', 'Fahey', 'Bioinformatics & Medical Informatics', '');
INSERT INTO members (first_name, last_name, major, status) VALUES ('Shyan', 'Polman', 'Bioinformatics & Medical Informatics', 'Auxillary');
INSERT INTO members (first_name, last_name, major, status) VALUES ('Surangi', 'Jayasinghe', 'Bioinformatics & Medical Informatics', 'Auxillary');
INSERT INTO members (first_name, last_name, major, status) VALUES ('Tony', 'Zamro', 'Bioinformatics & Medical Informatics', '');
INSERT INTO members (first_name, last_name, major, status) VALUES ('Trevor', 'Mugoya', 'Bioinformatics & Medical Informatics', 'Auxillary');
INSERT INTO members (first_name, last_name, major, status) VALUES ('Troy', 'Haynes', 'Bioinformatics & Medical Informatics', '');
INSERT INTO members (first_name, last_name, major, status) VALUES ('Zareeb', 'Lorenzana', 'Bioinformatics & Medical Informatics', 'VP Membership');